from .hr import HRAgent
from .finance import FinanceAgent
from .legal import LegalAgent
from .sales import SalesAgent
from .marketing import MarketingAgent
from .ops import OperationsAgent
from .it import ITAgent
from .procurement import ProcurementAgent
from .rd import RDAgent
from .customer_success import CustomerSuccessAgent
