"""
tests/test_auth_qa.py — QA Audit Test Suite for RAPID Auth System
Generated by Code QA Auditor  |  2026-05-24

Covers:
  - routers/auth.py         : login, refresh, logout, logout_all, change_password
  - routers/deps.py         : get_current_user, require_admin, require_role
  - infrastructure/user_registry.py : verify_password, hash_password, register_user, change_password

Run:
    cd <RAPID root>
    python -m pytest tests/test_auth_qa.py -v

Requirements:
    pip install pytest fastapi httpx pyjwt bcrypt pyyaml slowapi
"""
from __future__ import annotations

import os
import json
import sqlite3
import tempfile
from pathlib import Path
from unittest.mock import patch, MagicMock
from datetime import datetime, timedelta, timezone

import pytest
import yaml
import bcrypt
import jwt as pyjwt

# ── Set test env BEFORE any module import ─────────────────────────────────────
os.environ["JWT_SECRET_KEY"]                   = "test-secret-key-for-qa-only"
os.environ["JWT_ACCESS_TOKEN_EXPIRE_MINUTES"]  = "30"
os.environ["JWT_REFRESH_TOKEN_EXPIRE_DAYS"]    = "7"

from fastapi.testclient import TestClient
from fastapi import FastAPI, Depends, HTTPException

# ── Helpers ────────────────────────────────────────────────────────────────────

def _make_hash(password: str) -> str:
    """Return a bcrypt hash for use in fixture users.yaml."""
    return bcrypt.hashpw(password.encode(), bcrypt.gensalt(rounds=4)).decode()


def _make_users_yaml(tmp_path: Path, users: dict | None = None) -> Path:
    """
    Write a minimal users.yaml to tmp_path.
    Default provides one employee and one admin with known passwords.
    """
    if users is None:
        users = {
            "testuser": {
                "password_hash":         _make_hash("Passw0rd!"),
                "role":                  "employee",
                "name":                  "Test User",
                "email":                 "testuser@example.com",
                "rapid_user_id":         "USR-2026-0001",
                "permitted_departments": ["hr", "it"],
                "db_mode_enabled":       False,
            },
            "adminuser": {
                "password_hash":         _make_hash("AdminPass1!"),
                "role":                  "admin",
                "name":                  "Admin User",
                "email":                 "admin@example.com",
                "rapid_user_id":         "USR-2026-0002",
                "permitted_departments": ["hr", "it", "finance"],
                "db_mode_enabled":       False,
            },
        }
    p = tmp_path / "users.yaml"
    p.write_text(yaml.dump(users))
    return p


def _make_registry_json(tmp_path: Path) -> Path:
    """Write a blank user_registry.json."""
    p = tmp_path / "user_registry.json"
    p.write_text(json.dumps({"requests": {}, "counters": {"req": 0, "usr": 0}}, indent=2))
    return p


def _jwt_manager_with_tmp_db(tmp_path: Path, monkeypatch):
    """Return a fresh JWTManager backed by a temp SQLite DB."""
    import infrastructure.jwt_manager as jm
    db_path = str(tmp_path / "test_jwt.db")
    monkeypatch.setattr(jm, "DB_PATH", db_path)
    jm._jwt_manager = None  # reset singleton
    return jm.get_jwt_manager()


# ══════════════════════════════════════════════════════════════════════════════
# SECTION A: verify_password / hash_password
# ══════════════════════════════════════════════════════════════════════════════

class TestVerifyPassword:
    """T-29 through T-34 — core password verification logic."""

    def setup_method(self):
        from infrastructure.user_registry import hash_password, verify_password
        self.hash_password  = hash_password
        self.verify_password = verify_password

    def test_T29_correct_bcrypt_password_returns_true(self):
        """T-29: Correct bcrypt password is verified as True."""
        stored = self.hash_password("CorrectPass1")
        assert self.verify_password("CorrectPass1", stored) is True

    def test_T30_wrong_password_returns_false(self):
        """T-30: Wrong password returns False — must NOT pass auth."""
        stored = self.hash_password("CorrectPass1")
        assert self.verify_password("WrongPassword", stored) is False

    def test_T31_legacy_pbkdf2_hash_verified(self):
        """T-31: Legacy PBKDF2 hashes (salt$key format) are still accepted."""
        import hashlib, secrets
        salt = secrets.token_hex(16)
        key  = hashlib.pbkdf2_hmac("sha256", "LegacyPass".encode(), salt.encode(), 260_000).hex()
        stored = f"{salt}${key}"
        assert self.verify_password("LegacyPass", stored) is True
        assert self.verify_password("WrongPass",  stored) is False

    def test_T32_corrupt_hash_returns_false_not_crash(self):
        """T-32: Corrupt/malformed hash returns False — must not raise."""
        assert self.verify_password("anypassword", "notahash") is False
        assert self.verify_password("anypassword", "") is False
        assert self.verify_password("anypassword", "nodollar") is False

    def test_T33_empty_password_returns_false(self):
        """T-33: Empty string password must not authenticate."""
        stored = self.hash_password("RealPass123")
        assert self.verify_password("", stored) is False

    def test_T34_unicode_password_consistent(self):
        """T-34: Unicode passwords hash and verify consistently."""
        pw     = "pässwörd123"
        stored = self.hash_password(pw)
        assert self.verify_password(pw, stored) is True
        assert self.verify_password("passwrd123", stored) is False  # ASCII variant rejected


# ══════════════════════════════════════════════════════════════════════════════
# SECTION B: register_user()
# ══════════════════════════════════════════════════════════════════════════════

class TestRegisterUser:
    """T-35 through T-41 — self-registration validation."""

    @pytest.fixture(autouse=True)
    def _patch_paths(self, tmp_path, monkeypatch):
        """Redirect all file I/O to tmp_path."""
        import infrastructure.user_registry as ur
        users_yaml   = tmp_path / "users.yaml"
        registry_json = tmp_path / "user_registry.json"
        dept_heads   = tmp_path / "dept_heads.yaml"
        divisions    = tmp_path / "divisions.yaml"

        users_yaml.write_text(yaml.dump({}))
        registry_json.write_text(json.dumps({"requests": {}, "counters": {"req": 0, "usr": 0}}))
        dept_heads.write_text(yaml.dump({}))
        divisions.write_text(yaml.dump({}))

        monkeypatch.setattr(ur, "REGISTRY_PATH",   registry_json)
        monkeypatch.setattr(ur, "USERS_YAML",       users_yaml)
        monkeypatch.setattr(ur, "DEPT_HEADS_YAML",  dept_heads)
        monkeypatch.setattr(ur, "DIVISIONS_YAML",   divisions)

    def _valid_payload(self, **overrides):
        base = dict(
            employee_name   = "John Doe",
            org_email       = "john.doe@company.com",
            password        = "Secure123!",
            employee_id     = "EMP-001",
            requested_depts = ["hr"],
            justification   = "Need HR access for onboarding",
        )
        base.update(overrides)
        return base

    def test_T35_valid_registration_returns_request_id(self):
        """T-35: Valid registration returns a request dict with request_id at dept_review."""
        from infrastructure.user_registry import register_user
        result = register_user(**self._valid_payload())
        assert "request_id" in result
        assert result["stage"] == "dept_review"
        assert result["request_id"].startswith("REQ-")

    def test_T36_short_password_raises(self):
        """T-36: Password < 8 characters raises ValueError."""
        from infrastructure.user_registry import register_user
        with pytest.raises(ValueError, match="8 characters"):
            register_user(**self._valid_payload(password="short"))

    def test_T37_invalid_email_raises(self):
        """T-37: Email without '@' raises ValueError."""
        from infrastructure.user_registry import register_user
        with pytest.raises(ValueError, match="email"):
            register_user(**self._valid_payload(org_email="notanemail"))

    def test_T38_duplicate_email_raises(self, tmp_path):
        """T-38: Registering with an already-active email raises ValueError."""
        from infrastructure.user_registry import register_user
        # Register once successfully
        register_user(**self._valid_payload())
        # Second registration with same email — simulate approved user existing
        import infrastructure.user_registry as ur
        existing = yaml.safe_load(ur.USERS_YAML.read_text()) or {}
        existing["rapid_john"] = {
            "email": "john.doe@company.com",
            "role": "employee",
            "password_hash": _make_hash("Secure123!")
        }
        ur.USERS_YAML.write_text(yaml.dump(existing))
        with pytest.raises(ValueError, match="already exists"):
            register_user(**self._valid_payload(org_email="john.doe@company.com"))

    def test_T39_unknown_department_raises(self):
        """T-39: Unknown department in requested_depts raises ValueError."""
        from infrastructure.user_registry import register_user
        with pytest.raises(ValueError, match="Unknown department"):
            register_user(**self._valid_payload(requested_depts=["unicorn_dept"]))

    def test_T40_empty_departments_raises(self):
        """T-40: Empty requested_depts list raises ValueError."""
        from infrastructure.user_registry import register_user
        with pytest.raises(ValueError, match="at least one department"):
            register_user(**self._valid_payload(requested_depts=[]))

    def test_T41_password_hash_in_returned_request(self):
        """T-41: RISK — returned request dict contains password_hash (bcrypt format).
        This audits that the hash is bcrypt (not plaintext) and confirms R-06 risk exists.
        """
        from infrastructure.user_registry import register_user
        result = register_user(**self._valid_payload())
        assert "password_hash" in result
        assert result["password_hash"].startswith("$2b$"), \
            "password_hash must be bcrypt — plaintext password must NEVER be stored"


# ══════════════════════════════════════════════════════════════════════════════
# SECTION C: change_password() — registry function
# ══════════════════════════════════════════════════════════════════════════════

class TestChangePassword:
    """T-42 through T-46."""

    @pytest.fixture(autouse=True)
    def _setup(self, tmp_path, monkeypatch):
        import infrastructure.user_registry as ur
        users_yaml = tmp_path / "users.yaml"
        users = {
            "testuser": {
                "password_hash": _make_hash("OldPass123!"),
                "role": "employee",
                "email": "t@t.com",
            }
        }
        users_yaml.write_text(yaml.dump(users))
        monkeypatch.setattr(ur, "USERS_YAML", users_yaml)
        self._users_yaml = users_yaml

    def test_T42_valid_change_updates_hash(self):
        """T-42: Valid password change updates the hash in users.yaml."""
        from infrastructure.user_registry import change_password, verify_password
        change_password("testuser", "OldPass123!", "NewPass456!")
        updated = yaml.safe_load(self._users_yaml.read_text())
        new_hash = updated["testuser"]["password_hash"]
        assert verify_password("NewPass456!", new_hash) is True
        assert verify_password("OldPass123!", new_hash) is False

    def test_T43_wrong_current_password_blocked(self):
        """T-43: CRITICAL — wrong current password must raise ValueError."""
        from infrastructure.user_registry import change_password
        with pytest.raises(ValueError, match="incorrect"):
            change_password("testuser", "WrongOldPass", "NewPass456!")

    def test_T44_new_password_too_short_rejected(self):
        """T-44: New password < 8 chars raises ValueError."""
        from infrastructure.user_registry import change_password
        with pytest.raises(ValueError, match="8 characters"):
            change_password("testuser", "OldPass123!", "short")

    def test_T46_same_password_allowed(self):
        """T-46: Changing to the SAME password succeeds (no guard in code).
        This documents the gap — ideally should raise a warning.
        """
        from infrastructure.user_registry import change_password, verify_password
        # No exception expected — this is a gap, not a crash
        change_password("testuser", "OldPass123!", "OldPass123!")
        updated = yaml.safe_load(self._users_yaml.read_text())
        assert verify_password("OldPass123!", updated["testuser"]["password_hash"]) is True


# ══════════════════════════════════════════════════════════════════════════════
# SECTION D: JWTManager (supplement existing test_jwt.py)
# ══════════════════════════════════════════════════════════════════════════════

class TestJWTManagerSecurity:
    """Additional security-focused JWT tests not in test_jwt.py."""

    @pytest.fixture(autouse=True)
    def _manager(self, tmp_path, monkeypatch):
        self.manager = _jwt_manager_with_tmp_db(tmp_path, monkeypatch)

    def test_T06_default_secret_key_check(self):
        """T-06: CRITICAL — DEFAULT secret key 'CHANGE_ME_IN_PRODUCTION' should NOT be used.
        This test FAILS if the env var is not set, highlighting R-01.
        """
        secret = os.getenv("JWT_SECRET_KEY", "CHANGE_ME_IN_PRODUCTION")
        assert secret != "CHANGE_ME_IN_PRODUCTION", (
            "CRITICAL: JWT_SECRET_KEY is still the default. "
            "Any attacker can forge admin tokens."
        )

    def test_refresh_token_not_rotated_on_verify(self):
        """T-14 (R-02): Refresh token is NOT rotated — same token verifies twice.
        Documents the security gap: stolen tokens stay valid.
        """
        token = self.manager.create_refresh_token("alice")
        p1 = self.manager.verify_refresh_token(token)
        p2 = self.manager.verify_refresh_token(token)
        assert p1["jti"] == p2["jti"], "Token was rotated (unexpected — behaviour changed)"
        # NOTE: This test PASSES but documents the R-02 gap:
        # a stolen refresh token can be used indefinitely until expiry.

    def test_access_token_as_refresh_rejected(self):
        """T-12: Access token submitted to verify_refresh_token must be rejected."""
        access = self.manager.create_access_token("alice", "employee", [])
        with pytest.raises(ValueError, match="Not a refresh token"):
            self.manager.verify_refresh_token(access)

    def test_refresh_token_as_access_rejected(self):
        """T-24: Refresh token must be rejected by verify_access_token (type confusion guard)."""
        refresh = self.manager.create_refresh_token("alice")
        with pytest.raises(pyjwt.InvalidTokenError):
            self.manager.verify_access_token(refresh)

    def test_revoke_silently_succeeds_on_garbage_token(self):
        """T-19 / R-08: revoke_refresh_token with garbage input returns False — no crash."""
        result = self.manager.revoke_refresh_token("not.a.valid.jwt.token")
        assert result is False

    def test_revoke_all_returns_correct_count(self):
        """T-17: revoke_all_for_user returns count of revoked tokens."""
        self.manager.create_refresh_token("bob")
        self.manager.create_refresh_token("bob")
        self.manager.create_refresh_token("bob")
        count = self.manager.revoke_all_for_user("bob")
        assert count == 3


# ══════════════════════════════════════════════════════════════════════════════
# SECTION E: deps.py — get_current_user, require_admin, require_role
# ══════════════════════════════════════════════════════════════════════════════

class TestDependencies:
    """T-20 through T-28 — FastAPI auth dependencies."""

    @pytest.fixture(autouse=True)
    def _setup(self, tmp_path, monkeypatch):
        self.manager = _jwt_manager_with_tmp_db(tmp_path, monkeypatch)

        # Build a minimal FastAPI app with test routes
        from fastapi import FastAPI
        from routers.deps import get_current_user, require_admin, require_role
        app = FastAPI()

        @app.get("/protected")
        def protected(u=Depends(get_current_user)):
            return u

        @app.get("/admin-only")
        def admin_only(u=Depends(require_admin)):
            return u

        @app.get("/manager-or-admin")
        def mgr_or_admin(u=Depends(require_role("manager", "admin"))):
            return u

        from fastapi.testclient import TestClient
        self.client = TestClient(app, raise_server_exceptions=False)

    def _token(self, user_id="alice", role="employee", depts=None):
        return self.manager.create_access_token(user_id, role, depts or ["hr"])

    def test_T20_valid_token_returns_payload(self):
        """T-20: Valid Bearer token returns decoded payload."""
        token = self._token()
        resp  = self.client.get("/protected", headers={"Authorization": f"Bearer {token}"})
        assert resp.status_code == 200
        assert resp.json()["sub"] == "alice"

    def test_T21_no_auth_header_returns_401(self):
        """T-21: Missing Authorization header → 401."""
        resp = self.client.get("/protected")
        assert resp.status_code == 401

    def test_T22_expired_token_returns_401(self):
        """T-22: Expired access token → 401 with helpful message."""
        import infrastructure.jwt_manager as jm
        orig = jm.ACCESS_EXP
        jm.ACCESS_EXP = -1
        token = self.manager.create_access_token("alice", "employee", [])
        jm.ACCESS_EXP = orig
        resp = self.client.get("/protected", headers={"Authorization": f"Bearer {token}"})
        assert resp.status_code == 401
        assert "expired" in resp.json()["detail"].lower()

    def test_T23_tampered_token_returns_401(self):
        """T-23: CRITICAL — tampered token signature must be rejected."""
        token   = self._token()
        parts   = token.split(".")
        tampered = ".".join(parts[:2]) + ".INVALIDSIGNATUREXXXXXX"
        resp = self.client.get("/protected", headers={"Authorization": f"Bearer {tampered}"})
        assert resp.status_code == 401

    def test_T24_refresh_token_as_access_rejected(self):
        """T-24: CRITICAL — refresh token in Bearer header must be rejected."""
        refresh = self.manager.create_refresh_token("alice")
        resp = self.client.get("/protected", headers={"Authorization": f"Bearer {refresh}"})
        assert resp.status_code == 401

    def test_T25_admin_passes_require_admin(self):
        """T-25: Admin role passes require_admin."""
        token = self._token(role="admin")
        resp  = self.client.get("/admin-only", headers={"Authorization": f"Bearer {token}"})
        assert resp.status_code == 200

    def test_T26_employee_blocked_by_require_admin(self):
        """T-26: CRITICAL — employee role must be blocked from admin endpoints."""
        token = self._token(role="employee")
        resp  = self.client.get("/admin-only", headers={"Authorization": f"Bearer {token}"})
        assert resp.status_code == 403
        assert "Admin" in resp.json()["detail"]

    def test_T27_require_role_multiple_roles(self):
        """T-27: require_role accepts any of the specified roles."""
        for role in ("manager", "admin"):
            token = self._token(role=role)
            resp  = self.client.get("/manager-or-admin", headers={"Authorization": f"Bearer {token}"})
            assert resp.status_code == 200, f"Role '{role}' should be allowed"

    def test_T28_missing_role_key_treated_as_non_admin(self):
        """T-28: Token payload with no 'role' key must not pass require_admin."""
        import infrastructure.jwt_manager as jm
        # Build a token manually with no 'role' field
        now = datetime.now(timezone.utc)
        payload = {"sub": "ghost", "depts": [], "iat": now, "exp": now + timedelta(minutes=30), "type": "access"}
        token = pyjwt.encode(payload, jm.SECRET_KEY, algorithm=jm.ALGORITHM)
        resp = self.client.get("/admin-only", headers={"Authorization": f"Bearer {token}"})
        assert resp.status_code == 403


# ══════════════════════════════════════════════════════════════════════════════
# SECTION F: /auth/login endpoint (integration)
# ══════════════════════════════════════════════════════════════════════════════

class TestLoginEndpoint:
    """T-01 through T-08 — /auth/login route integration tests."""

    @pytest.fixture(autouse=True)
    def _setup(self, tmp_path, monkeypatch):
        self.tmp_path = tmp_path
        self.users_yaml = _make_users_yaml(tmp_path)

        # Redirect USERS_YAML so _get_user_db_path() → tmp_path/users.db (clean per-test)
        import infrastructure.user_registry as ur
        monkeypatch.setattr(ur, "USERS_YAML", self.users_yaml)
        # DB is now at tmp_path/users.db — empty on first call → YAML fallback works

        # Patch JWT DB
        import infrastructure.jwt_manager as jm
        db_path = str(tmp_path / "jwt.db")
        monkeypatch.setattr(jm, "DB_PATH", db_path)
        jm._jwt_manager = None

        # Reset the auth-specific rate limiter storage so sequential tests
        # don't accumulate against each other's IP counter.
        # The module-level _auth_limiter persists across test methods; clearing
        # it here gives each test a fresh slate without disabling rate limiting.
        from routers.auth import _auth_limiter
        try:
            _auth_limiter._storage.reset()
        except Exception:
            # Fallback: clear the underlying MemoryStorage dicts directly
            try:
                _auth_limiter._storage._events.clear()
                _auth_limiter._storage._timer_map.clear()
            except Exception:
                pass  # If all else fails, the 10/minute limit is high enough

        # Build a minimal FastAPI app
        from fastapi import FastAPI
        from routers.auth import router
        from fastapi.responses import JSONResponse
        from slowapi.errors import RateLimitExceeded
        app = FastAPI()
        app.include_router(router)
        from slowapi import Limiter
        from slowapi.util import get_remote_address
        from slowapi.middleware import SlowAPIMiddleware
        app.add_middleware(SlowAPIMiddleware)
        app.state.limiter = Limiter(key_func=get_remote_address)

        # Add the same login-specific 429 message as in main.py
        @app.exception_handler(RateLimitExceeded)
        async def _rate_limit_handler(request, exc):
            if "/auth/login" in request.url.path:
                return JSONResponse(
                    status_code=429,
                    content={"detail": "Too many login attempts. Please wait 60 seconds and try again."},
                )
            return JSONResponse(status_code=429, content={"detail": str(exc)})

        self.users_yaml_content = self.users_yaml.read_text()

        from fastapi.testclient import TestClient
        self.client = TestClient(app, raise_server_exceptions=False)

    def _post_login(self, user_id, password):
        # No YAML/Path patching needed — USERS_YAML is redirected to tmp in _setup.
        # _load_users() tries DB (empty → 0 count) then falls back to USERS_YAML (tmp).
        return self.client.post("/auth/login", json={"user_id": user_id, "password": password})

    def test_T01_valid_login_returns_tokens(self):
        """T-01: Happy path — valid credentials return access + refresh tokens."""
        resp = self._post_login("testuser", "Passw0rd!")
        assert resp.status_code == 200
        data = resp.json()
        assert "access_token"  in data
        assert "refresh_token" in data
        assert data["token_type"] == "bearer"
        assert data["user_id"]    == "testuser"

    def test_T02_wrong_password_returns_401(self):
        """T-02: Wrong password → 401 Invalid credentials."""
        resp = self._post_login("testuser", "WrongPassword")
        assert resp.status_code == 401
        assert "Invalid credentials" in resp.json()["detail"]

    def test_T03_unknown_user_returns_401(self):
        """T-03: Non-existent user_id → 401. Must NOT distinguish 'user not found' from 'wrong pass'."""
        resp = self._post_login("ghost_user", "anypassword")
        assert resp.status_code == 401
        assert "Invalid credentials" in resp.json()["detail"]
        # Verify same message as wrong password (no user enumeration)
        resp2 = self._post_login("testuser", "WrongPass!")
        assert resp.json()["detail"] == resp2.json()["detail"], \
            "Different error messages for 'user not found' vs 'wrong password' — enables user enumeration"

    def test_T04_empty_password_returns_401(self):
        """T-04: Empty password string must not authenticate."""
        resp = self._post_login("testuser", "")
        assert resp.status_code == 401

    def test_T05_missing_users_yaml_returns_401(self):
        """T-05: If no users exist (empty DB + no YAML), login returns 401 (not 500)."""
        import infrastructure.user_registry as ur
        # Point USERS_YAML at a nonexistent file so DB falls back to it and gets {}
        from pathlib import Path as _Path
        nonexistent = self.tmp_path / "no_such_users.yaml"
        with patch.object(ur, "USERS_YAML", nonexistent):
            resp = self.client.post("/auth/login", json={"user_id": "testuser", "password": "Passw0rd!"})
        assert resp.status_code == 401

    def test_T07_admin_login_returns_correct_role(self):
        """T-07: Admin login response includes role='admin'."""
        resp = self._post_login("adminuser", "AdminPass1!")
        assert resp.status_code == 200
        assert resp.json()["role"] == "admin"

    def test_T08_user_with_no_password_hash_returns_401(self):
        """T-08: User record missing password_hash → 401, not 500."""
        import yaml as _yaml
        users = _yaml.safe_load(self.users_yaml_content) or {}
        users["nohash"] = {"role": "employee", "name": "No Hash"}  # no password_hash key
        patched_yaml = _yaml.dump(users)
        with patch("pathlib.Path.exists", return_value=True), \
             patch("pathlib.Path.read_text", return_value=patched_yaml):
            resp = self.client.post("/auth/login", json={"user_id": "nohash", "password": "anything"})
        assert resp.status_code == 401


# ══════════════════════════════════════════════════════════════════════════════
# SECTION G: /auth/refresh endpoint (integration)
# ══════════════════════════════════════════════════════════════════════════════

class TestRefreshEndpoint:
    """T-09 through T-14."""

    @pytest.fixture(autouse=True)
    def _setup(self, tmp_path, monkeypatch):
        self.tmp_path = tmp_path
        self.users_yaml = _make_users_yaml(tmp_path)
        self.users_yaml_content = self.users_yaml.read_text()

        # Redirect USERS_YAML so _get_user_db_path() → tmp_path/users.db (clean per-test)
        import infrastructure.user_registry as ur
        monkeypatch.setattr(ur, "USERS_YAML", self.users_yaml)

        import infrastructure.jwt_manager as jm
        db_path = str(tmp_path / "jwt.db")
        monkeypatch.setattr(jm, "DB_PATH", db_path)
        jm._jwt_manager = None
        self.manager = jm.get_jwt_manager()

        from fastapi import FastAPI
        from routers.auth import router
        from slowapi import Limiter
        from slowapi.util import get_remote_address
        from slowapi.middleware import SlowAPIMiddleware
        app = FastAPI()
        app.include_router(router)
        app.add_middleware(SlowAPIMiddleware)
        app.state.limiter = Limiter(key_func=get_remote_address)

        from fastapi.testclient import TestClient
        self.client = TestClient(app, raise_server_exceptions=False)

    def _refresh(self, token):
        # No YAML/Path patching needed — USERS_YAML is redirected to tmp in _setup.
        return self.client.post("/auth/refresh", json={"refresh_token": token})

    def test_T09_valid_refresh_returns_new_access_token(self):
        """T-09: Valid refresh token returns new access token."""
        token = self.manager.create_refresh_token("testuser")
        resp  = self._refresh(token)
        assert resp.status_code == 200
        data = resp.json()
        assert "access_token" in data
        assert data["token_type"] == "bearer"

    def test_T10_revoked_refresh_token_returns_401(self):
        """T-10: CRITICAL — revoked refresh token must not yield new access token."""
        token = self.manager.create_refresh_token("testuser")
        self.manager.revoke_refresh_token(token)
        resp  = self._refresh(token)
        assert resp.status_code == 401
        assert "revoked" in resp.json()["detail"].lower()

    def test_T11_expired_refresh_token_returns_401(self):
        """T-11: Expired refresh token returns 401."""
        import infrastructure.jwt_manager as jm
        orig = jm.REFRESH_EXP
        jm.REFRESH_EXP = -1
        token = self.manager.create_refresh_token("testuser")
        jm.REFRESH_EXP = orig
        resp = self._refresh(token)
        assert resp.status_code == 401

    def test_T12_access_token_as_refresh_rejected(self):
        """T-12: Access token sent to /auth/refresh must be rejected."""
        access = self.manager.create_access_token("testuser", "employee", ["hr"])
        resp   = self._refresh(access)
        assert resp.status_code == 401

    def test_T13_deleted_user_refresh_returns_401(self):
        """T-13: If user is removed from the user store, refresh must return 401."""
        token = self.manager.create_refresh_token("testuser")
        # Simulate user deletion: point USERS_YAML at an empty file (DB is also empty)
        import infrastructure.user_registry as ur
        empty_yaml_path = self.tmp_path / "empty_users.yaml"
        empty_yaml_path.write_text(yaml.dump({}))
        with patch.object(ur, "USERS_YAML", empty_yaml_path):
            resp = self.client.post("/auth/refresh", json={"refresh_token": token})
        assert resp.status_code == 401
        assert "no longer exists" in resp.json()["detail"].lower()

    def test_T14_refresh_token_not_rotated(self):
        """T-14 (R-02 RISK AUDIT): Same refresh token can be used twice — documents gap."""
        token = self.manager.create_refresh_token("testuser")
        resp1 = self._refresh(token)
        resp2 = self._refresh(token)
        assert resp1.status_code == 200, "First use should succeed"
        assert resp2.status_code == 200, "Second use also succeeds — token NOT rotated (R-02 gap)"


# ══════════════════════════════════════════════════════════════════════════════
# SECTION H: /auth/logout integration
# ══════════════════════════════════════════════════════════════════════════════

class TestLogoutEndpoint:
    """T-15 through T-19."""

    @pytest.fixture(autouse=True)
    def _setup(self, tmp_path, monkeypatch):
        import infrastructure.jwt_manager as jm
        db_path = str(tmp_path / "jwt.db")
        monkeypatch.setattr(jm, "DB_PATH", db_path)
        jm._jwt_manager = None
        self.manager = jm.get_jwt_manager()

        from fastapi import FastAPI
        from routers.auth import router
        from slowapi import Limiter
        from slowapi.util import get_remote_address
        from slowapi.middleware import SlowAPIMiddleware
        app = FastAPI()
        app.include_router(router)
        app.add_middleware(SlowAPIMiddleware)
        app.state.limiter = Limiter(key_func=get_remote_address)

        from fastapi.testclient import TestClient
        self.client = TestClient(app, raise_server_exceptions=False)

        # Create an access token for authenticated calls
        self.access_token = self.manager.create_access_token("testuser", "employee", ["hr"])

    def _auth_headers(self):
        return {"Authorization": f"Bearer {self.access_token}"}

    def test_T15_logout_revokes_refresh_token(self):
        """T-15: Logout returns 200 and revokes the refresh token."""
        refresh = self.manager.create_refresh_token("testuser")
        resp = self.client.post(
            "/auth/logout",
            json={"refresh_token": refresh},
            headers=self._auth_headers(),
        )
        assert resp.status_code == 200
        # Verify token is now revoked
        with pytest.raises(ValueError, match="revoked"):
            self.manager.verify_refresh_token(refresh)

    def test_T16_refresh_rejected_after_logout(self):
        """T-16: CRITICAL — refresh token submitted to /auth/refresh after logout must fail."""
        users_content = yaml.dump({"testuser": {"role": "employee", "permitted_departments": ["hr"], "password_hash": _make_hash("x")}})
        refresh = self.manager.create_refresh_token("testuser")
        # Logout
        self.client.post("/auth/logout", json={"refresh_token": refresh}, headers=self._auth_headers())
        # Try to refresh
        with patch("pathlib.Path.exists", return_value=True), \
             patch("pathlib.Path.read_text", return_value=users_content):
            resp = self.client.post("/auth/refresh", json={"refresh_token": refresh})
        assert resp.status_code == 401

    def test_T17_logout_all_revokes_all_tokens(self):
        """T-17: /auth/logout-all revokes all refresh tokens for user."""
        t1 = self.manager.create_refresh_token("testuser")
        t2 = self.manager.create_refresh_token("testuser")
        t3 = self.manager.create_refresh_token("testuser")
        resp = self.client.post("/auth/logout-all", headers=self._auth_headers())
        assert resp.status_code == 200
        assert "3" in resp.json()["message"]  # "Logged out from 3 device(s)"
        for t in (t1, t2, t3):
            with pytest.raises(ValueError):
                self.manager.verify_refresh_token(t)

    def test_T18_cannot_revoke_another_users_token(self):
        """T-18 FIXED: Cross-user refresh-token revocation is blocked with 403.

        The logout endpoint decodes the submitted refresh token (signature not
        verified to handle expired tokens gracefully) and compares its 'sub' to
        the authenticated user's 'sub'.  A mismatch → 403 Forbidden.
        User B's token must remain valid after the rejected attempt.
        """
        # Create user B's refresh token (user B != testuser)
        other_refresh = self.manager.create_refresh_token("otheruser")

        # User A (testuser) attempts to revoke user B's token
        resp = self.client.post(
            "/auth/logout",
            json={"refresh_token": other_refresh},
            headers=self._auth_headers(),  # testuser's access token
        )
        # Ownership check must reject this with 403
        assert resp.status_code == 403, (
            "logout must return 403 when the refresh token's sub "
            "does not match the authenticated user's sub"
        )
        assert "belong to you" in resp.json().get("detail", "").lower()

        # User B's token must still be valid — the revocation was refused
        payload = self.manager.verify_refresh_token(other_refresh)
        assert payload["sub"] == "otheruser", "User B's token was wrongly revoked"

    def test_T19_logout_already_revoked_token_idempotent(self):
        """T-19: Logging out with an already-revoked token returns 200 (idempotent)."""
        refresh = self.manager.create_refresh_token("testuser")
        self.manager.revoke_refresh_token(refresh)
        resp = self.client.post("/auth/logout", json={"refresh_token": refresh}, headers=self._auth_headers())
        assert resp.status_code == 200


# ══════════════════════════════════════════════════════════════════════════════
# SECTION I: Task 2 — User DB storage integration tests
# ══════════════════════════════════════════════════════════════════════════════

class TestUserDatabase:
    """Verify that users are persisted to and read from SQLite (Task 2)."""

    @pytest.fixture(autouse=True)
    def _setup(self, tmp_path, monkeypatch):
        import infrastructure.user_registry as ur
        self.tmp_path = tmp_path
        # Redirect USERS_YAML → tmp so DB also lives in tmp
        self.users_yaml = tmp_path / "users.yaml"
        self.users_yaml.write_text(yaml.dump({}))
        monkeypatch.setattr(ur, "USERS_YAML", self.users_yaml)
        self.ur = ur

    def _make_user(self, login_key: str, password: str = "Pass1234!", role: str = "employee") -> dict:
        return {
            "name": login_key.capitalize(),
            "role": role,
            "email": f"{login_key}@example.com",
            "password_hash": _make_hash(password),
            "permitted_departments": ["hr"],
            "db_mode_enabled": False,
        }

    def test_init_creates_table(self):
        """init_user_db() creates the users table without error."""
        self.ur.init_user_db()
        conn = self.ur._db_connect()
        rows = conn.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name='users'"
        ).fetchall()
        conn.close()
        assert len(rows) == 1

    def test_seed_from_yaml_on_empty_db(self):
        """On empty DB, init_user_db() seeds users from users.yaml."""
        users = {"alice": self._make_user("alice")}
        self.users_yaml.write_text(yaml.dump(users))
        self.ur.init_user_db()
        loaded = self.ur.load_users()
        assert "alice" in loaded

    def test_seed_does_not_overwrite_existing_db(self):
        """init_user_db() is a no-op when DB already has users."""
        # Write "alice" directly to DB
        self.ur._db_save_all_users({"alice": self._make_user("alice")})
        # YAML has "bob" — should NOT overwrite DB content
        self.users_yaml.write_text(yaml.dump({"bob": self._make_user("bob")}))
        self.ur.init_user_db()
        loaded = self.ur.load_users()
        assert "alice" in loaded
        assert "bob" not in loaded  # YAML seeding skipped

    def test_load_users_returns_db_users_when_populated(self):
        """load_users() returns from DB when DB has records."""
        user_data = self._make_user("carol")
        self.ur._db_save_all_users({"carol": user_data})
        loaded = self.ur.load_users()
        assert "carol" in loaded
        assert loaded["carol"]["role"] == "employee"

    def test_save_users_persists_to_db_and_yaml(self):
        """_save_users() writes to BOTH DB and the YAML backup."""
        users = {"dave": self._make_user("dave")}
        self.ur._save_users(users)
        # DB check
        db_users = self.ur._db_load_all_users()
        assert "dave" in db_users
        # YAML check (write-through backup)
        yaml_users = yaml.safe_load(self.users_yaml.read_text()) or {}
        assert "dave" in yaml_users

    def test_permitted_departments_round_trips_correctly(self):
        """List fields survive DB round-trip as Python lists (not JSON strings)."""
        user_data = self._make_user("eve")
        user_data["permitted_departments"] = ["hr", "finance", "legal"]
        self.ur._db_save_all_users({"eve": user_data})
        loaded = self.ur.load_users()
        assert loaded["eve"]["permitted_departments"] == ["hr", "finance", "legal"]

    def test_tenant_id_round_trips_through_the_database(self):
        """Tenant identity must survive DB-backed user storage and JWT login seeding."""
        user_data = self._make_user("tenant_user")
        user_data["tenant_id"] = "tenant-alpha"
        self.ur._db_save_all_users({"tenant_user": user_data})

        loaded = self.ur.load_users()
        assert loaded["tenant_user"]["tenant_id"] == "tenant-alpha"

    def test_load_falls_back_to_yaml_when_db_empty(self):
        """When DB has no records, load_users() falls back to YAML."""
        users = {"fallback_user": self._make_user("fallback_user")}
        self.users_yaml.write_text(yaml.dump(users))
        # Don't populate DB — load should fall back to YAML
        loaded = self.ur.load_users()
        assert "fallback_user" in loaded

    def test_change_password_updates_db(self):
        """change_password() updates the user record in the DB (via _save_users)."""
        users = {"frank": self._make_user("frank", password="OldPass1!")}
        self.ur._save_users(users)
        self.ur.change_password("frank", "OldPass1!", "NewPass1!")
        db_users = self.ur._db_load_all_users()
        # New hash must verify the new password
        from infrastructure.user_registry import verify_password
        assert verify_password("NewPass1!", db_users["frank"]["password_hash"])
        assert not verify_password("OldPass1!", db_users["frank"]["password_hash"])
