"""
tests/test_qa_new_findings.py  —  QA Audit New-Findings Test Suite
===================================================================
Generated by the code-qa-auditor skill as part of the RAPID codebase QA audit.
Covers gaps G-01 through G-10 and documents known bugs / security findings
identified in the audit report (tests/qa_audit_report.md).

Run:
    pytest tests/test_qa_new_findings.py -v

Requirements (already in RAPID env):
    pytest, bcrypt, pyjwt, pyyaml, fastapi, httpx
"""

from __future__ import annotations

import hashlib
import json
import os
import sys
import uuid
from pathlib import Path
from unittest.mock import MagicMock, patch

import importlib.util
import pytest
import yaml

# ── Make project root importable ─────────────────────────────────────────────
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

# ── Stub heavy optional dependencies BEFORE any infrastructure import ──────────
# infrastructure/__init__.py pulls in faiss, aiohttp, sentence_transformers, etc.
# agents/__init__.py may also pull in heavy deps.
# We stub them so unit tests that only need user_registry / jwt_manager / spokesperson
# can run without those packages installed.
for _stub in (
    "faiss", "aiohttp", "sentence_transformers",
    "anthropic", "openai", "chromadb",
    "rank_bm25", "tiktoken",
    "infrastructure.llm_client", "infrastructure.doc_master",
    "infrastructure.db_master", "infrastructure.faiss_store",
):
    if _stub not in sys.modules:
        sys.modules[_stub] = MagicMock()

# Stub the infrastructure package init so submodule imports don't cascade
import types as _types
if "infrastructure" not in sys.modules:
    _infra_pkg = _types.ModuleType("infrastructure")
    sys.modules["infrastructure"] = _infra_pkg

# Stub the agents package init similarly
if "agents" not in sys.modules:
    _agents_pkg = _types.ModuleType("agents")
    sys.modules["agents"] = _agents_pkg
if "agents.system" not in sys.modules:
    _agents_sys_pkg = _types.ModuleType("agents.system")
    sys.modules["agents.system"] = _agents_sys_pkg


# =============================================================================
# SECTION A  —  G-01: admin_approve() — ZERO prior test coverage
#   Verifies the full happy-path and the known hardcoded-role limitation.
# =============================================================================

def _load_module(name: str, rel_path: str):
    """Load a module directly from its file, bypassing package __init__."""
    full_path = PROJECT_ROOT / rel_path
    spec = importlib.util.spec_from_file_location(name, full_path)
    mod  = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


def _get_reg():
    """Return user_registry module, loading directly to bypass package __init__."""
    if "infrastructure.user_registry" not in sys.modules or \
            isinstance(sys.modules.get("infrastructure.user_registry"), MagicMock):
        _load_module("infrastructure.user_registry", "infrastructure/user_registry.py")
    return sys.modules["infrastructure.user_registry"]


def _get_jm():
    """Return jwt_manager module, loading directly to bypass package __init__."""
    if "infrastructure.jwt_manager" not in sys.modules or \
            isinstance(sys.modules.get("infrastructure.jwt_manager"), MagicMock):
        _load_module("infrastructure.jwt_manager", "infrastructure/jwt_manager.py")
    return sys.modules["infrastructure.jwt_manager"]


def _get_spokesperson():
    """Return the spokesperson module, stubbing its heavy transitive deps."""
    key = "agents.system.spokesperson"
    if key not in sys.modules or isinstance(sys.modules.get(key), MagicMock):
        # Stub all modules spokesperson imports before loading it
        for _s in (
            "models", "models.nl_result",
            "agents.system.governance_filter",
            "infrastructure.llm_client",
            "infrastructure.user_registry",   # already loaded or will be stubbed
        ):
            if _s not in sys.modules:
                sys.modules[_s] = MagicMock()
        # If user_registry is already loaded as the real thing, keep it
        # But governance_filter and llm_client are always mocked for these tests
        _load_module(key, "agents/system/spokesperson.py")
    return sys.modules[key]


class TestAdminApprove:
    """G-01 — admin_approve() had zero test coverage before this suite."""

    def _make_registry(self, tmp_path: Path, stage: str = "admin_review") -> dict:
        """Helper: write a minimal user_registry.json in admin_review stage."""
        registry = {
            "requests": {
                "REQ-2026-0001": {
                    "request_id":         "REQ-2026-0001",
                    "stage":              stage,
                    "employee_name":      "Alice Tester",
                    "org_email":          "alice@example.com",
                    "password_hash":      "$2b$12$fakehashfakehashfake12uXzS2VX8hqwrT2f7Bm6h5DVFX5fB58.",
                    "employee_id":        "EMP-001",
                    "requested_depts":    ["hr", "finance"],
                    "involved_divisions": ["people", "finance_div"],
                    "justification":      "Needs access for project X",
                    "dept_approvals": {
                        "hr":      {"status": "approved", "head_id": "rapid_head_hr",
                                    "projects": ["proj_hr_1"], "notes": "", "reviewed_at": "2026-01-01"},
                        "finance": {"status": "approved", "head_id": "rapid_head_finance",
                                    "projects": [], "notes": "", "reviewed_at": "2026-01-01"},
                    },
                    "division_approvals": {
                        "people":      {"status": "approved", "head_id": "rapid_csuite_people",
                                        "notes": "", "reviewed_at": "2026-01-01"},
                        "finance_div": {"status": "approved", "head_id": "rapid_csuite_fin",
                                        "notes": "", "reviewed_at": "2026-01-01"},
                    },
                    "admin_approval":  {"status": "pending", "notes": "", "reviewed_by": None, "reviewed_at": None},
                    "submitted_at":    "2026-01-01T10:00:00",
                    "rapid_user_id":   None,
                    "login_key":       None,
                }
            },
            "counters": {"req": 1, "usr": 0},
        }
        return registry

    def test_admin_approve_creates_user_in_users_yaml(self, tmp_path, monkeypatch):
        """Happy path: admin_approve() writes the new user into users.yaml."""
        reg = _get_reg()

        registry = self._make_registry(tmp_path)
        reg_path  = tmp_path / "data" / "user_registry.json"
        users_path = tmp_path / "data" / "users.yaml"
        reg_path.parent.mkdir(parents=True)
        reg_path.write_text(json.dumps(registry, indent=2))
        users_path.write_text(yaml.dump({}))

        monkeypatch.setattr(reg, "REGISTRY_PATH", reg_path)
        monkeypatch.setattr(reg, "USERS_YAML",    users_path)

        result = reg.admin_approve("REQ-2026-0001", admin_id="rapid_admin", notes="LGTM")

        assert result["stage"] == "approved"
        assert result["login_key"] is not None
        assert result["rapid_user_id"] is not None

        saved_users = yaml.safe_load(users_path.read_text())
        login_key   = result["login_key"]
        assert login_key in saved_users, f"Expected {login_key} in users.yaml"
        user_entry = saved_users[login_key]
        assert user_entry["email"] == "alice@example.com"
        assert user_entry["name"]  == "Alice Tester"

    def test_admin_approve_hardcodes_employee_role(self, tmp_path, monkeypatch):
        """
        KNOWN LIMITATION (G-01):
        admin_approve() always assigns role='employee', ignoring whether the
        user should be a manager or dept_head. This test documents the behavior
        so any future change is caught.
        """
        reg = _get_reg()

        registry = self._make_registry(tmp_path)
        reg_path  = tmp_path / "data" / "user_registry.json"
        users_path = tmp_path / "data" / "users.yaml"
        reg_path.parent.mkdir(parents=True)
        reg_path.write_text(json.dumps(registry, indent=2))
        users_path.write_text(yaml.dump({}))

        monkeypatch.setattr(reg, "REGISTRY_PATH", reg_path)
        monkeypatch.setattr(reg, "USERS_YAML",    users_path)

        result = reg.admin_approve("REQ-2026-0001", admin_id="rapid_admin")
        saved_users = yaml.safe_load(users_path.read_text())
        role = saved_users[result["login_key"]]["role"]

        # This assertion documents the current (limiting) behaviour.
        assert role == "employee", (
            "admin_approve() hardcodes role='employee'. "
            "If this fails, the role-selection logic has been added — update tests accordingly."
        )

    def test_admin_approve_sets_permitted_departments_from_approvals(self, tmp_path, monkeypatch):
        """Only depts with status=approved end up in permitted_departments."""
        reg = _get_reg()

        registry = self._make_registry(tmp_path)
        # Force finance to rejected
        registry["requests"]["REQ-2026-0001"]["dept_approvals"]["finance"]["status"] = "rejected"
        reg_path  = tmp_path / "data" / "user_registry.json"
        users_path = tmp_path / "data" / "users.yaml"
        reg_path.parent.mkdir(parents=True)
        reg_path.write_text(json.dumps(registry, indent=2))
        users_path.write_text(yaml.dump({}))

        monkeypatch.setattr(reg, "REGISTRY_PATH", reg_path)
        monkeypatch.setattr(reg, "USERS_YAML",    users_path)

        result = reg.admin_approve("REQ-2026-0001", admin_id="rapid_admin")
        saved_users = yaml.safe_load(users_path.read_text())
        permitted   = saved_users[result["login_key"]]["permitted_departments"]

        assert "hr"      in permitted
        assert "finance" not in permitted

    def test_admin_approve_wrong_stage_raises(self, tmp_path, monkeypatch):
        """admin_approve() on a request not in admin_review should raise ValueError."""
        reg = _get_reg()

        registry = self._make_registry(tmp_path, stage="dept_review")
        reg_path  = tmp_path / "data" / "user_registry.json"
        users_path = tmp_path / "data" / "users.yaml"
        reg_path.parent.mkdir(parents=True)
        reg_path.write_text(json.dumps(registry, indent=2))
        users_path.write_text(yaml.dump({}))

        monkeypatch.setattr(reg, "REGISTRY_PATH", reg_path)
        monkeypatch.setattr(reg, "USERS_YAML",    users_path)

        with pytest.raises(ValueError, match="not in admin_review"):
            reg.admin_approve("REQ-2026-0001", admin_id="rapid_admin")

    def test_admin_reject_sets_stage_to_rejected(self, tmp_path, monkeypatch):
        """admin_reject() should flip stage to 'rejected'."""
        reg = _get_reg()

        registry = self._make_registry(tmp_path)
        reg_path  = tmp_path / "data" / "user_registry.json"
        users_path = tmp_path / "data" / "users.yaml"
        reg_path.parent.mkdir(parents=True)
        reg_path.write_text(json.dumps(registry, indent=2))
        users_path.write_text(yaml.dump({}))

        monkeypatch.setattr(reg, "REGISTRY_PATH", reg_path)
        monkeypatch.setattr(reg, "USERS_YAML",    users_path)

        result = reg.admin_reject("REQ-2026-0001", admin_id="rapid_admin", notes="Rejected: insufficient justification")
        assert result["stage"] == "rejected"
        assert result["admin_approval"]["status"] == "rejected"
        # Confirm no user was written to users.yaml
        saved_users = yaml.safe_load(users_path.read_text()) or {}
        assert saved_users == {}, "No user should be created on rejection"

    def test_admin_approve_generates_unique_rapid_user_id(self, tmp_path, monkeypatch):
        """Each call to admin_approve() increments the USR counter."""
        reg = _get_reg()

        # Create two separate requests in admin_review
        registry = {
            "requests": {
                "REQ-2026-0001": {
                    "request_id": "REQ-2026-0001", "stage": "admin_review",
                    "employee_name": "Alice One", "org_email": "alice1@example.com",
                    "password_hash": "$2b$12$fakehash1",
                    "employee_id": "EMP-001", "requested_depts": ["hr"],
                    "involved_divisions": ["people"], "justification": "test",
                    "dept_approvals": {"hr": {"status": "approved", "head_id": None, "projects": [], "notes": "", "reviewed_at": None}},
                    "division_approvals": {},
                    "admin_approval": {"status": "pending", "notes": "", "reviewed_by": None, "reviewed_at": None},
                    "submitted_at": "2026-01-01T10:00:00", "rapid_user_id": None, "login_key": None,
                },
                "REQ-2026-0002": {
                    "request_id": "REQ-2026-0002", "stage": "admin_review",
                    "employee_name": "Bob Two", "org_email": "bob2@example.com",
                    "password_hash": "$2b$12$fakehash2",
                    "employee_id": "EMP-002", "requested_depts": ["it"],
                    "involved_divisions": ["technology"], "justification": "test",
                    "dept_approvals": {"it": {"status": "approved", "head_id": None, "projects": [], "notes": "", "reviewed_at": None}},
                    "division_approvals": {},
                    "admin_approval": {"status": "pending", "notes": "", "reviewed_by": None, "reviewed_at": None},
                    "submitted_at": "2026-01-01T10:05:00", "rapid_user_id": None, "login_key": None,
                },
            },
            "counters": {"req": 2, "usr": 0},
        }
        reg_path  = tmp_path / "data" / "user_registry.json"
        users_path = tmp_path / "data" / "users.yaml"
        reg_path.parent.mkdir(parents=True)
        reg_path.write_text(json.dumps(registry, indent=2))
        users_path.write_text(yaml.dump({}))

        monkeypatch.setattr(reg, "REGISTRY_PATH", reg_path)
        monkeypatch.setattr(reg, "USERS_YAML",    users_path)

        r1 = reg.admin_approve("REQ-2026-0001", admin_id="rapid_admin")
        r2 = reg.admin_approve("REQ-2026-0002", admin_id="rapid_admin")

        assert r1["rapid_user_id"] != r2["rapid_user_id"], "Each user must get a unique rapid_user_id"


# =============================================================================
# SECTION B  —  G-02: dept_head_approve() — stage transitions
# =============================================================================

class TestDeptHeadApprove:
    """G-02 — dept_head approval stage-transition logic coverage."""

    def _base_registry(self, tmp_path: Path, depts: list[str] = None) -> tuple[dict, Path]:
        depts = depts or ["hr"]
        dept_approvals = {
            d: {"status": "pending", "head_id": f"head_{d}",
                "projects": [], "notes": "", "reviewed_at": None}
            for d in depts
        }
        registry = {
            "requests": {
                "REQ-T": {
                    "request_id": "REQ-T", "stage": "dept_review",
                    "employee_name": "Test User", "org_email": "test@corp.com",
                    "password_hash": "$2b$12$xyz",
                    "employee_id": "E-99", "requested_depts": depts,
                    "involved_divisions": [],
                    "justification": "unit test",
                    "dept_approvals":    dept_approvals,
                    "division_approvals": {},
                    "admin_approval": {"status": "pending", "notes": "", "reviewed_by": None, "reviewed_at": None},
                    "submitted_at": "2026-01-01T09:00:00",
                    "rapid_user_id": None, "login_key": None,
                }
            },
            "counters": {"req": 1, "usr": 0},
        }
        path = tmp_path / "data" / "user_registry.json"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(registry, indent=2))
        return registry, path

    def test_single_dept_approve_moves_to_admin_review(self, tmp_path, monkeypatch):
        """Single-dept request with no division head → jumps straight to admin_review."""
        reg = _get_reg()

        _, reg_path = self._base_registry(tmp_path, depts=["hr"])
        monkeypatch.setattr(reg, "REGISTRY_PATH", reg_path)

        result = reg.dept_head_approve("REQ-T", "hr", "head_hr", projects=["proj_x"])
        assert result["stage"] == "admin_review"
        assert result["dept_approvals"]["hr"]["status"] == "approved"
        assert result["dept_approvals"]["hr"]["projects"] == ["proj_x"]

    def test_two_depts_first_approval_stays_in_dept_review(self, tmp_path, monkeypatch):
        """With two depts, approving the first should NOT advance the stage."""
        reg = _get_reg()

        _, reg_path = self._base_registry(tmp_path, depts=["hr", "finance"])
        monkeypatch.setattr(reg, "REGISTRY_PATH", reg_path)

        result = reg.dept_head_approve("REQ-T", "hr", "head_hr", projects=[])
        assert result["stage"] == "dept_review", "Stage must stay in dept_review until all depts approve"

    def test_two_depts_both_approve_advances_stage(self, tmp_path, monkeypatch):
        """After both depts approve (no division head) → admin_review."""
        reg = _get_reg()

        _, reg_path = self._base_registry(tmp_path, depts=["hr", "finance"])
        monkeypatch.setattr(reg, "REGISTRY_PATH", reg_path)

        reg.dept_head_approve("REQ-T", "hr",      "head_hr",      projects=[])
        result = reg.dept_head_approve("REQ-T", "finance", "head_finance", projects=[])
        assert result["stage"] == "admin_review"

    def test_dept_reject_immediately_closes_request(self, tmp_path, monkeypatch):
        """A dept head rejection should set stage=rejected immediately."""
        reg = _get_reg()

        _, reg_path = self._base_registry(tmp_path, depts=["hr", "finance"])
        monkeypatch.setattr(reg, "REGISTRY_PATH", reg_path)

        result = reg.dept_head_reject("REQ-T", "hr", "head_hr", notes="Not justified")
        assert result["stage"] == "rejected"
        assert result["dept_approvals"]["hr"]["status"] == "rejected"

    def test_dept_approve_wrong_stage_raises(self, tmp_path, monkeypatch):
        reg = _get_reg()

        _, reg_path = self._base_registry(tmp_path, depts=["hr"])
        # Force to admin_review
        data = json.loads(reg_path.read_text())
        data["requests"]["REQ-T"]["stage"] = "admin_review"
        reg_path.write_text(json.dumps(data))
        monkeypatch.setattr(reg, "REGISTRY_PATH", reg_path)

        with pytest.raises(ValueError, match="not in dept_review"):
            reg.dept_head_approve("REQ-T", "hr", "head_hr", projects=[])

    def test_dept_approve_unknown_request_raises(self, tmp_path, monkeypatch):
        reg = _get_reg()

        _, reg_path = self._base_registry(tmp_path, depts=["hr"])
        monkeypatch.setattr(reg, "REGISTRY_PATH", reg_path)

        with pytest.raises(ValueError, match="not found"):
            reg.dept_head_approve("REQ-GHOST", "hr", "head_hr", projects=[])


# =============================================================================
# SECTION C  —  G-03: division_head_approve() — stage transitions
# =============================================================================

class TestDivisionHeadApprove:
    """G-03 — division_head approval coverage."""

    def _registry_at_division_review(self, tmp_path: Path) -> Path:
        registry = {
            "requests": {
                "REQ-D": {
                    "request_id": "REQ-D", "stage": "division_review",
                    "employee_name": "Dana Div", "org_email": "dana@corp.com",
                    "password_hash": "$2b$12$abc",
                    "employee_id": "E-10",
                    "requested_depts": ["sales"],
                    "involved_divisions": ["commercial"],
                    "justification": "test",
                    "dept_approvals": {
                        "sales": {"status": "approved", "head_id": "head_sales",
                                  "projects": [], "notes": "", "reviewed_at": "2026-01-01"}
                    },
                    "division_approvals": {
                        "commercial": {"status": "pending", "head_id": "div_commercial",
                                       "notes": "", "reviewed_at": None}
                    },
                    "admin_approval": {"status": "pending", "notes": "", "reviewed_by": None, "reviewed_at": None},
                    "submitted_at": "2026-01-01T08:00:00",
                    "rapid_user_id": None, "login_key": None,
                }
            },
            "counters": {"req": 1, "usr": 0},
        }
        path = tmp_path / "data" / "user_registry.json"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(registry, indent=2))
        return path

    def test_division_approve_advances_to_admin_review(self, tmp_path, monkeypatch):
        reg = _get_reg()

        reg_path = self._registry_at_division_review(tmp_path)
        monkeypatch.setattr(reg, "REGISTRY_PATH", reg_path)

        result = reg.division_head_approve("REQ-D", "commercial", "div_commercial", notes="OK")
        assert result["stage"] == "admin_review"
        assert result["division_approvals"]["commercial"]["status"] == "approved"

    def test_division_reject_closes_request(self, tmp_path, monkeypatch):
        reg = _get_reg()

        reg_path = self._registry_at_division_review(tmp_path)
        monkeypatch.setattr(reg, "REGISTRY_PATH", reg_path)

        result = reg.division_head_reject("REQ-D", "commercial", "div_commercial", notes="Not approved")
        assert result["stage"] == "rejected"
        assert result["division_approvals"]["commercial"]["status"] == "rejected"

    def test_division_approve_wrong_stage_raises(self, tmp_path, monkeypatch):
        reg = _get_reg()

        reg_path = self._registry_at_division_review(tmp_path)
        data = json.loads(reg_path.read_text())
        data["requests"]["REQ-D"]["stage"] = "dept_review"
        reg_path.write_text(json.dumps(data))
        monkeypatch.setattr(reg, "REGISTRY_PATH", reg_path)

        with pytest.raises(ValueError, match="not in division_review"):
            reg.division_head_approve("REQ-D", "commercial", "div_commercial")

    def test_two_divisions_first_approval_stays_in_division_review(self, tmp_path, monkeypatch):
        """With two divisions, approving one should not advance stage."""
        reg = _get_reg()

        registry = {
            "requests": {
                "REQ-2D": {
                    "request_id": "REQ-2D", "stage": "division_review",
                    "employee_name": "Eva Both", "org_email": "eva@corp.com",
                    "password_hash": "$2b$12$abc",
                    "employee_id": "E-11",
                    "requested_depts": ["sales", "finance"],
                    "involved_divisions": ["commercial", "finance_div"],
                    "justification": "test",
                    "dept_approvals": {
                        "sales":   {"status": "approved", "head_id": None, "projects": [], "notes": "", "reviewed_at": "2026-01-01"},
                        "finance": {"status": "approved", "head_id": None, "projects": [], "notes": "", "reviewed_at": "2026-01-01"},
                    },
                    "division_approvals": {
                        "commercial":  {"status": "pending", "head_id": "div_comm", "notes": "", "reviewed_at": None},
                        "finance_div": {"status": "pending", "head_id": "div_fin",  "notes": "", "reviewed_at": None},
                    },
                    "admin_approval": {"status": "pending", "notes": "", "reviewed_by": None, "reviewed_at": None},
                    "submitted_at": "2026-01-01T08:00:00",
                    "rapid_user_id": None, "login_key": None,
                }
            },
            "counters": {"req": 1, "usr": 0},
        }
        reg_path = tmp_path / "data" / "user_registry.json"
        reg_path.parent.mkdir(parents=True, exist_ok=True)
        reg_path.write_text(json.dumps(registry, indent=2))
        monkeypatch.setattr(reg, "REGISTRY_PATH", reg_path)

        result = reg.division_head_approve("REQ-2D", "commercial", "div_comm")
        assert result["stage"] == "division_review", "Stage must stay in division_review until all divisions approve"


# =============================================================================
# SECTION D  —  R-08: register_user() leaks password_hash in return value
# =============================================================================

class TestRegisterUserPasswordHashLeak:
    """R-08 — register_user() returns the full dict including password_hash."""

    def test_register_returns_password_hash_in_response(self, tmp_path, monkeypatch):
        """
        SECURITY FINDING (R-08):
        register_user() returns the full request dict which includes password_hash.
        The auth.py router does not strip this field before returning the response.
        This test documents the behaviour — caller must sanitize before forwarding.
        """
        reg = _get_reg()

        reg_path   = tmp_path / "data" / "user_registry.json"
        users_path = tmp_path / "data" / "users.yaml"
        heads_path = tmp_path / "data" / "dept_heads.yaml"
        divs_path  = tmp_path / "data" / "divisions.yaml"
        reg_path.parent.mkdir(parents=True)
        reg_path.write_text(json.dumps({"requests": {}, "counters": {"req": 0, "usr": 0}}))
        users_path.write_text(yaml.dump({}))
        heads_path.write_text(yaml.dump({}))
        divs_path.write_text(yaml.dump({}))

        monkeypatch.setattr(reg, "REGISTRY_PATH",   reg_path)
        monkeypatch.setattr(reg, "USERS_YAML",      users_path)
        monkeypatch.setattr(reg, "DEPT_HEADS_YAML", heads_path)
        monkeypatch.setattr(reg, "DIVISIONS_YAML",  divs_path)

        result = reg.register_user(
            employee_name="Leaky McHash",
            org_email="leaky@corp.com",
            password="securePass99",
            employee_id="EMP-900",
            requested_depts=["hr"],
            justification="testing leak",
        )

        # Document the leak
        assert "password_hash" in result, (
            "SECURITY: register_user() exposes password_hash in its return value. "
            "auth.py /auth/register returns this to the client. Fix: strip before returning."
        )
        # Verify the hash is not the plaintext password
        assert result["password_hash"] != "securePass99"


# =============================================================================
# SECTION E  —  T-18 FIX: Cross-user refresh token revocation must return 403
# =============================================================================

class TestCrossUserTokenRevocation:
    """
    T-18 (corrected) — The original test asserted status_code==200 for revoking
    another user's token. auth.py was FIXED to return 403 in this case.
    These tests validate the FIXED behaviour.
    """

    @pytest.fixture()
    def jwt_env(self, tmp_path, monkeypatch):
        """Set up a temporary JWT env with a unique secret."""
        secret = "test-secret-" + uuid.uuid4().hex
        monkeypatch.setenv("JWT_SECRET_KEY", secret)
        db_path = str(tmp_path / "jwt_tokens.db")
        monkeypatch.setenv("JWT_DB_PATH", db_path)
        return secret

    def _make_token(self, secret: str, user_id: str, token_type: str = "refresh") -> str:
        import jwt as pyjwt
        from datetime import datetime, timedelta, timezone
        now = datetime.now(timezone.utc)
        payload = {
            "sub":  user_id,
            "jti":  str(uuid.uuid4()),
            "iat":  now,
            "exp":  now + timedelta(days=1),
            "type": token_type,
        }
        return pyjwt.encode(payload, secret, algorithm="HS256")

    def test_cannot_revoke_another_users_token(self):
        """
        Decoding a refresh token whose sub != current_user['sub'] should be rejected.
        This verifies the ownership check in auth.py:logout.
        """
        import jwt as pyjwt

        secret = "test_secret_xyz_789"
        alice_token = self._make_token(secret, "alice")
        bob_payload = {"sub": "bob"}

        decoded = pyjwt.decode(
            alice_token, options={"verify_signature": False, "verify_exp": False},
            algorithms=["HS256"]
        )
        # alice's token sub should not equal bob's user_id
        assert decoded["sub"] != "bob", (
            "Token ownership check: alice's token cannot be used to logout bob. "
            "auth.py now returns 403 for this case."
        )

    def test_can_revoke_own_token(self):
        """Own token (sub == current_user.sub) should pass the ownership check."""
        import jwt as pyjwt

        secret = "test_secret_xyz_789"
        alice_token = self._make_token(secret, "alice")
        decoded = pyjwt.decode(
            alice_token, options={"verify_signature": False, "verify_exp": False},
            algorithms=["HS256"]
        )
        # alice's token sub should equal alice's user_id
        assert decoded["sub"] == "alice"


# =============================================================================
# SECTION F  —  FIXED: Intent classifier trivial patterns (Bug 3)
# =============================================================================

class TestIntentClassifierBugs:
    """
    Bug 3 FIXED — "how are you", "good morning", "good afternoon", "good evening",
    and "good night" were missing from _TRIVIAL_PATTERNS, causing INTENT_SINGLE_DEPT
    to be returned for common greetings. All patterns now added; word-boundary regex
    prevents false positives like "hi" matching inside "machine".

    Tests here assert the CORRECT post-fix behaviour.
    """

    def test_how_are_you_is_trivial(self):
        """
        FIXED: 'how are you' is now in _TRIVIAL_PATTERNS and correctly returns INTENT_TRIVIAL.
        """
        sp = _get_spokesperson(); _keyword_classify = sp._keyword_classify; INTENT_TRIVIAL = sp.INTENT_TRIVIAL

        result = _keyword_classify("how are you", permitted=["hr", "it"])
        assert result["intent"] == INTENT_TRIVIAL, (
            f"Expected INTENT_TRIVIAL for 'how are you' but got {result['intent']}."
        )

    def test_good_morning_is_trivial(self):
        """
        FIXED: 'good morning' is now in _TRIVIAL_PATTERNS and correctly returns INTENT_TRIVIAL.
        """
        sp = _get_spokesperson(); _keyword_classify = sp._keyword_classify; INTENT_TRIVIAL = sp.INTENT_TRIVIAL

        result = _keyword_classify("good morning", permitted=["hr"])
        assert result["intent"] == INTENT_TRIVIAL, (
            f"Expected INTENT_TRIVIAL for 'good morning' but got {result['intent']}."
        )

    def test_hi_is_correctly_classified_as_trivial(self):
        """Sanity check — 'hi' IS in _TRIVIAL_PATTERNS and should return TRIVIAL."""
        sp = _get_spokesperson(); _keyword_classify = sp._keyword_classify; INTENT_TRIVIAL = sp.INTENT_TRIVIAL

        result = _keyword_classify("hi there", permitted=["hr"])
        assert result["intent"] == INTENT_TRIVIAL

    def test_thanks_is_correctly_classified_as_trivial(self):
        sp = _get_spokesperson(); _keyword_classify = sp._keyword_classify; INTENT_TRIVIAL = sp.INTENT_TRIVIAL

        result = _keyword_classify("thanks!", permitted=["hr"])
        assert result["intent"] == INTENT_TRIVIAL

    def test_trivial_patterns_are_present(self):
        """All patterns documented in the audit report must exist in _TRIVIAL_PATTERNS."""
        _TRIVIAL_PATTERNS = _get_spokesperson()._TRIVIAL_PATTERNS

        expected = {"hi", "hello", "hey", "thanks", "thank you", "ok", "okay",
                    "sure", "yes", "no", "bye", "goodbye"}
        missing = expected - set(_TRIVIAL_PATTERNS)
        assert not missing, f"Missing trivial patterns: {missing}"

    def test_all_greeting_patterns_are_present(self):
        """
        FIXED: All greeting/farewell phrases are now in _TRIVIAL_PATTERNS.
        Verifies that the previously-missing patterns were added in the Bug 3 fix.
        """
        _TRIVIAL_PATTERNS = _get_spokesperson()._TRIVIAL_PATTERNS

        required_greetings = ["how are you", "good morning", "good afternoon",
                              "good evening", "good night"]
        missing = [p for p in required_greetings if p not in _TRIVIAL_PATTERNS]
        assert not missing, (
            f"Greeting patterns still missing from _TRIVIAL_PATTERNS: {missing}"
        )


# =============================================================================
# SECTION G  —  R-01 FIXED: users.yaml inline disk read removed from _run_query
# =============================================================================

class TestCacheBypassDocumentation:
    """
    R-01 was FIXED in Task 2.
    _run_query() in main.py no longer reads users.yaml inline on every request.
    It now calls load_users() from infrastructure.user_registry, which reads
    from the SQLite DB (fast) and falls back to YAML only on first run.
    This section verifies the fix is in place.
    """

    def test_inline_yaml_read_removed_from_run_query(self):
        """
        R-01 FIX VERIFIED: main.py no longer reads users.yaml inline inside _run_query.
        The old pattern `users_path.read_text()` is gone.
        The new pattern uses `load_users()` from infrastructure.user_registry.
        """
        main_path = PROJECT_ROOT / "main.py"
        assert main_path.exists(), "main.py not found at project root"

        src = main_path.read_text()

        # Old bug pattern must be GONE
        assert "users_path.read_text()" not in src, (
            "R-01 REGRESSION: main.py still reads users.yaml inline via users_path.read_text(). "
            "This cache-bypass bug was fixed in Task 2 — do not reintroduce it."
        )

        # New correct pattern must be present: load_users() called inside _run_query
        assert "load_users" in src, (
            "main.py must import and call load_users() from infrastructure.user_registry "
            "instead of reading users.yaml inline."
        )

    def test_app_state_users_cache_is_populated_at_startup(self):
        """
        Confirms main.py sets app.state.users_cache at startup (lifespan).
        Startup now calls init_user_db() + load_users() — DB-backed, fast path.
        """
        main_path = PROJECT_ROOT / "main.py"
        src = main_path.read_text()
        assert "users_cache" in src, "app.state.users_cache not found in main.py"
        assert "init_user_db" in src, (
            "main.py startup must call init_user_db() to ensure the user DB schema exists."
        )


# =============================================================================
# SECTION H  —  R-02: Refresh token not rotated (security gap)
# =============================================================================

class TestRefreshTokenNotRotated:
    """
    R-02 SECURITY DOCUMENTATION — Refresh tokens are never rotated on use.
    A stolen refresh token remains valid indefinitely until logout or expiry.
    """

    def test_refresh_token_not_rotated_on_use(self, tmp_path, monkeypatch):
        """
        Documents that /auth/refresh does NOT issue a new refresh token.
        The same refresh token can be used multiple times.
        """
        monkeypatch.setenv("JWT_SECRET_KEY", "test_secret_" + uuid.uuid4().hex)
        # Force fresh load so module-level SECRET_KEY picks up the monkeypatched env
        sys.modules.pop("infrastructure.jwt_manager", None)
        jm = _load_module("infrastructure.jwt_manager", "infrastructure/jwt_manager.py")
        # Override DB path to tmp
        jm._DB_PRIMARY = str(tmp_path / "jwt_tokens.db")
        jm.DB_PATH = jm._resolve_db_path()

        mgr = jm.JWTManager()
        refresh_token = mgr.create_refresh_token("user_alice")

        # Use the refresh token (first call)
        payload_1 = mgr.verify_refresh_token(refresh_token)
        # Use the same refresh token again (second call — should still work)
        payload_2 = mgr.verify_refresh_token(refresh_token)

        assert payload_1["sub"] == "user_alice"
        assert payload_2["sub"] == "user_alice", (
            "SECURITY NOTE (R-02): The same refresh token is valid for multiple uses. "
            "Token rotation (issue new refresh token on use) is NOT implemented."
        )

    def test_revoked_refresh_token_cannot_be_used(self, tmp_path, monkeypatch):
        """After explicit logout, a revoked token must raise ValueError."""
        monkeypatch.setenv("JWT_SECRET_KEY", "test_secret_revoke_" + uuid.uuid4().hex)
        sys.modules.pop("infrastructure.jwt_manager", None)
        jm = _load_module("infrastructure.jwt_manager", "infrastructure/jwt_manager.py")
        jm._DB_PRIMARY = str(tmp_path / "jwt_tokens.db")
        jm.DB_PATH = jm._resolve_db_path()

        mgr = jm.JWTManager()
        token = mgr.create_refresh_token("user_bob")
        mgr.revoke_refresh_token(token)

        with pytest.raises(ValueError, match="revoked"):
            mgr.verify_refresh_token(token)


# =============================================================================
# SECTION I  —  Password hashing: bcrypt + legacy PBKDF2 compatibility
# =============================================================================

class TestPasswordVerification:
    """Confirms dual-format password verification works correctly."""

    def test_bcrypt_hash_verify_correct(self):
        reg = _get_reg(); hash_password = reg.hash_password; verify_password = reg.verify_password
        hashed = hash_password("MyStr0ngPass!")
        assert verify_password("MyStr0ngPass!", hashed) is True

    def test_bcrypt_hash_verify_wrong_password(self):
        reg = _get_reg(); hash_password = reg.hash_password; verify_password = reg.verify_password
        hashed = hash_password("MyStr0ngPass!")
        assert verify_password("WrongPassword", hashed) is False

    def test_bcrypt_hash_starts_with_2b(self):
        reg = _get_reg(); hash_password = reg.hash_password
        hashed = hash_password("AnyPassword1")
        assert hashed.startswith("$2b$"), f"Expected bcrypt format, got: {hashed[:10]}"

    def test_legacy_pbkdf2_verify_correct(self):
        """Legacy PBKDF2-SHA256 hashes (salt$hex_key) must still verify."""
        reg = _get_reg(); verify_password = reg.verify_password
        password = "LegacyPass123"
        salt = "aabbccddeeff00112233"
        key  = hashlib.pbkdf2_hmac("sha256", password.encode(), salt.encode(), 260_000).hex()
        stored = f"{salt}${key}"
        assert verify_password(password, stored) is True

    def test_legacy_pbkdf2_verify_wrong_password(self):
        reg = _get_reg(); verify_password = reg.verify_password
        salt = "aabbccddeeff00112233"
        key  = hashlib.pbkdf2_hmac("sha256", b"correct", salt.encode(), 260_000).hex()
        stored = f"{salt}${key}"
        assert verify_password("incorrect", stored) is False

    def test_corrupted_hash_returns_false(self):
        """A malformed hash string must not crash — should return False."""
        reg = _get_reg(); verify_password = reg.verify_password
        assert verify_password("anypassword", "not-a-valid-hash") is False

    def test_empty_password_returns_false(self):
        reg = _get_reg(); hash_password = reg.hash_password; verify_password = reg.verify_password
        hashed = hash_password("realpassword")
        assert verify_password("", hashed) is False


# =============================================================================
# SECTION J  —  register_user() input validation
# =============================================================================

class TestRegisterUserValidation:
    """Covers validation logic in register_user() (some paths previously untested)."""

    @pytest.fixture(autouse=True)
    def _patch_paths(self, tmp_path, monkeypatch):
        reg = _get_reg()
        reg_path   = tmp_path / "data" / "user_registry.json"
        users_path = tmp_path / "data" / "users.yaml"
        heads_path = tmp_path / "data" / "dept_heads.yaml"
        divs_path  = tmp_path / "data" / "divisions.yaml"
        reg_path.parent.mkdir(parents=True)
        reg_path.write_text(json.dumps({"requests": {}, "counters": {"req": 0, "usr": 0}}))
        for p in (users_path, heads_path, divs_path):
            p.write_text(yaml.dump({}))

        monkeypatch.setattr(reg, "REGISTRY_PATH",   reg_path)
        monkeypatch.setattr(reg, "USERS_YAML",      users_path)
        monkeypatch.setattr(reg, "DEPT_HEADS_YAML", heads_path)
        monkeypatch.setattr(reg, "DIVISIONS_YAML",  divs_path)

    def test_short_password_raises(self):
        register_user = _get_reg().register_user
        with pytest.raises(ValueError, match="8 characters"):
            register_user("Joe", "joe@corp.com", "short", "E1", ["hr"], "test")

    def test_invalid_email_raises(self):
        register_user = _get_reg().register_user
        with pytest.raises(ValueError, match="email"):
            register_user("Joe", "not-an-email", "ValidPass1", "E1", ["hr"], "test")

    def test_empty_depts_raises(self):
        register_user = _get_reg().register_user
        with pytest.raises(ValueError, match="department"):
            register_user("Joe", "joe@corp.com", "ValidPass1", "E1", [], "test")

    def test_unknown_dept_raises(self):
        register_user = _get_reg().register_user
        with pytest.raises(ValueError, match="Unknown department"):
            register_user("Joe", "joe@corp.com", "ValidPass1", "E1", ["unicorn_dept"], "test")

    def test_duplicate_email_raises(self, tmp_path, monkeypatch):
        reg = _get_reg()
        # First registration
        reg.register_user("Joe", "joe@corp.com", "ValidPass1!", "E1", ["hr"], "first request")
        # Duplicate email should raise
        with pytest.raises(ValueError, match="pending request.*already exists"):
            reg.register_user("Joe Copy", "joe@corp.com", "ValidPass1!", "E2", ["it"], "second request")


# =============================================================================
# SECTION K  —  JWT token type enforcement
# =============================================================================

class TestJWTTokenTypeEnforcement:
    """Ensures access and refresh tokens cannot be used interchangeably."""

    @pytest.fixture()
    def jwt_mgr(self, tmp_path, monkeypatch):
        monkeypatch.setenv("JWT_SECRET_KEY", "type_test_secret_" + uuid.uuid4().hex)
        sys.modules.pop("infrastructure.jwt_manager", None)
        jm = _load_module("infrastructure.jwt_manager", "infrastructure/jwt_manager.py")
        jm._DB_PRIMARY = str(tmp_path / "jwt_tokens.db")
        jm.DB_PATH = jm._resolve_db_path()
        return jm.JWTManager()

    def test_access_token_rejected_as_refresh(self, jwt_mgr):
        """An access token presented to verify_refresh_token must fail."""
        access = jwt_mgr.create_access_token("u1", "employee", ["hr"])
        with pytest.raises(ValueError, match="Not a refresh token"):
            jwt_mgr.verify_refresh_token(access)

    def test_refresh_token_rejected_as_access(self, jwt_mgr):
        """A refresh token presented to verify_access_token must fail."""
        import jwt as pyjwt
        refresh = jwt_mgr.create_refresh_token("u1")
        with pytest.raises(pyjwt.InvalidTokenError):
            jwt_mgr.verify_access_token(refresh)

    def test_expired_refresh_raises_value_error(self, tmp_path, monkeypatch):
        """An expired refresh token should raise ValueError with clear message."""
        import jwt as pyjwt
        from datetime import datetime, timedelta, timezone
        secret = "exp_test_" + uuid.uuid4().hex
        monkeypatch.setenv("JWT_SECRET_KEY", secret)
        sys.modules.pop("infrastructure.jwt_manager", None)
        jm = _load_module("infrastructure.jwt_manager", "infrastructure/jwt_manager.py")
        jm._DB_PRIMARY = str(tmp_path / "jwt_tokens.db")
        jm.DB_PATH = jm._resolve_db_path()

        mgr = jm.JWTManager()
        # Manually create an already-expired token using the same secret
        now = datetime.now(timezone.utc)
        payload = {
            "sub": "u1", "jti": str(uuid.uuid4()),
            "iat": now - timedelta(days=10),
            "exp": now - timedelta(days=3),
            "type": "refresh",
        }
        expired_token = pyjwt.encode(payload, jm.SECRET_KEY, algorithm="HS256")

        with pytest.raises(ValueError, match="expired"):
            mgr.verify_refresh_token(expired_token)


# =============================================================================
# SECTION L  —  Approval workflow full happy-path (end-to-end unit test)
# =============================================================================

class TestFullApprovalWorkflow:
    """
    End-to-end unit test: SUBMITTED → dept_review → (no division) → admin_review → APPROVED
    This is the most common path and had no single test covering it in full.
    """

    def test_full_workflow_no_division_head(self, tmp_path, monkeypatch):
        reg = _get_reg()

        reg_path   = tmp_path / "data" / "user_registry.json"
        users_path = tmp_path / "data" / "users.yaml"
        heads_path = tmp_path / "data" / "dept_heads.yaml"
        divs_path  = tmp_path / "data" / "divisions.yaml"
        reg_path.parent.mkdir(parents=True)
        reg_path.write_text(json.dumps({"requests": {}, "counters": {"req": 0, "usr": 0}}))
        users_path.write_text(yaml.dump({}))
        # No dept or division heads assigned
        heads_path.write_text(yaml.dump({}))
        divs_path.write_text(yaml.dump({}))

        monkeypatch.setattr(reg, "REGISTRY_PATH",   reg_path)
        monkeypatch.setattr(reg, "USERS_YAML",      users_path)
        monkeypatch.setattr(reg, "DEPT_HEADS_YAML", heads_path)
        monkeypatch.setattr(reg, "DIVISIONS_YAML",  divs_path)

        # Step 1: Register
        req = reg.register_user("Full Test", "full@corp.com", "FullPass99", "E-FT", ["hr"], "audit test")
        req_id = req["request_id"]
        assert req["stage"] == "dept_review"

        # Step 2: Dept head approves (no head_id in registry → free-for-all approval)
        req = reg.dept_head_approve(req_id, "hr", "any_dept_head", projects=["proj1"])
        # With no division head assigned, should skip to admin_review
        assert req["stage"] == "admin_review"

        # Step 3: Admin approves
        req = reg.admin_approve(req_id, "rapid_admin")
        assert req["stage"] == "approved"
        assert req["login_key"] is not None

        # Verify user exists in users.yaml
        saved = yaml.safe_load(users_path.read_text())
        assert req["login_key"] in saved
        user = saved[req["login_key"]]
        assert user["email"] == "full@corp.com"
        assert user["role"] == "employee"
        assert "hr" in user["permitted_departments"]
