import { ArrowRight, Check, Clock3, LockKeyhole, Sparkles } from 'lucide-react';
import { Link } from 'react-router-dom';

export function BetaLandingPage() {
  return <main className="beta-page">
    <nav className="beta-nav" aria-label="Primary navigation"><Link className="product-brand" to="/"><span>R</span><strong>RAPID</strong></Link><div><a href="#workflow">How it works</a><Link className="product-button secondary compact" to="/login">Sign in</Link></div></nav>
    <section className="beta-hero">
      <div className="beta-hero-copy"><p className="beta-kicker"><Sparkles size={14} /> Private beta for startup teams</p><h1>Run the weekly review that keeps your company aligned.</h1><p>RAPID brings delivery, customer risk, pipeline, decisions, and ownership into one operating picture your team can act on.</p><div className="beta-actions"><Link className="product-button primary" to="/start">Request beta access <ArrowRight size={15} /></Link><Link className="text-button" to="/login">I have an invite</Link></div><p className="beta-note"><LockKeyhole size={14} /> Every approved team starts in an isolated sample workspace. No production system is connected by default.</p></div>
      <div className="beta-product-preview" aria-label="RAPID product preview"><div className="beta-preview-bar"><span className="beta-preview-brand"><b>R</b> RAPID</span><span>Northstar Labs</span><i>Weekly review</i></div><div className="beta-preview-body"><aside><small>WORKSPACE</small><b>Overview</b><span>Meetings</span><span>Actions</span><small>OPERATING DATA</small><span>Customers</span><span>Projects</span></aside><section><p>Operating review</p><h2>This week, what needs a decision?</h2><div className="beta-preview-signal"><span>Customer risk</span><strong>Atlas renewal recovery plan needs an owner.</strong><em>Customer Success · high priority</em></div><div className="beta-preview-list"><div><span>Delivery</span><b>Publish migration guidance for v2.8</b><i>In progress</i></div><div><span>People</span><b>Validate Q3 hiring capacity</b><i>Open</i></div></div></section></div></div>
    </section>
    <section id="workflow" className="beta-flow"><div><h2>One operating rhythm, without another status meeting.</h2><p>Use RAPID before, during, and after the review so the company leaves with decisions, owners, and visible follow-through.</p></div><ol><li><b>Apply</b><span>Tell us about your startup and the operating work you want to test.</span></li><li><b>Activate</b><span>Once approved, set up your founder account in an isolated sample workspace.</span></li><li><b>Operate</b><span>Run reviews, capture decisions, and track accountable follow-through.</span></li></ol></section>
    <section className="beta-trust"><div><p className="beta-kicker">Built for deliberate adoption</p><h2>Useful on day one. Controlled when you connect real data.</h2></div><ul><li><Check size={16} /> Synthetic evaluation workspace for every approved team</li><li><Check size={16} /> Source-aware answers with visible evidence</li><li><Check size={16} /> Human approval for consequential work</li><li><Clock3 size={16} /> Founder-led beta access, reviewed before activation</li></ul></section>
    <footer className="beta-footer"><span>RAPID private beta</span><Link to="/login">Sign in</Link><Link to="/start">Request access</Link></footer>
  </main>;
}
